#!/usr/bin/env node
/* ============================================================
   Build: src/ -> www/
   ============================================================
   The app has no framework and no dependencies, and www/ stays
   plain static files you can serve with anything. This script
   exists only so the parts that are genuinely shared between the
   shelf and every chapter — the storage adapter, the mission
   engine, the base stylesheet — live in exactly one file.

     node scripts/build.js            build
     node scripts/build.js --check    verify www/ matches src/

   A source file pulls a shared part in with an include marker on
   a line of its own. Both spellings do the same thing; use the
   one that is a comment in the surrounding language — a slash-star
   marker inside <script> or <style>, an HTML comment inside markup:

     SLASH-STAR @include shared/engine.js STAR-SLASH
     <!--@include shared/head.html-->

   Paths are relative to src/. Includes may nest.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'www');
const MARKER = /^[ \t]*(?:\/\*@include\s+(\S+?)\s*\*\/|<!--@include\s+(\S+?)\s*-->)[ \t]*$/;
const MAX_DEPTH = 8;
const BANNER = '<!-- Generated by scripts/build.js from src/. Do not edit www/ by hand. -->';

function expand(file, depth, seen) {
  if (depth > MAX_DEPTH) throw new Error('include nested deeper than ' + MAX_DEPTH + ': ' + file);
  return fs.readFileSync(file, 'utf8').split('\n').map(line => {
    const m = line.match(MARKER);
    if (!m) return line;
    const rel = m[1] || m[2];
    const target = path.join(SRC, rel);
    if (!target.startsWith(SRC + path.sep)) throw new Error('include escapes src/: ' + rel);
    if (!fs.existsSync(target)) throw new Error('no such include: ' + rel + ' (from ' + path.relative(ROOT, file) + ')');
    seen.add(rel);
    return expand(target, depth + 1, seen).replace(/\n$/, '');
  }).join('\n');
}

function render(file) {
  const seen = new Set();
  let out = expand(file, 0, seen);
  // stamp the banner so nobody edits the generated copy by mistake
  out = out.replace(/^(<!DOCTYPE html>\n)/i, '$1' + BANNER + '\n');
  return { text: out, includes: seen };
}

const pages = [
  path.join(SRC, 'index.html'),
  ...fs.readdirSync(path.join(SRC, 'chapters')).filter(f => f.endsWith('.html')).sort()
    .map(f => path.join(SRC, 'chapters', f))
];

const check = process.argv.includes('--check');
let stale = 0;

for (const page of pages) {
  const { text, includes } = render(page);
  const dest = path.join(OUT, path.basename(page));
  const current = fs.existsSync(dest) ? fs.readFileSync(dest, 'utf8') : null;
  const from = [...includes].sort().join(', ') || 'no includes';
  if (current === text) {
    console.log('  ok      ' + path.basename(dest) + '  (' + from + ')');
  } else if (check) {
    console.log('  STALE   ' + path.basename(dest) + '  (' + from + ')');
    stale++;
  } else {
    fs.writeFileSync(dest, text);
    console.log('  wrote   ' + path.basename(dest) + '  (' + from + ')');
  }
}

if (check && stale) {
  console.error('\n' + stale + ' file(s) in www/ do not match src/. Run: npm run build');
  process.exit(1);
}
if (!check) console.log('\nDone. Bump VERSION in www/service-worker.js so caches refresh.');
